package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMultimall;
import org.linlinjava.litemall.db.domain.LitemallMultimallExample;

public interface LitemallMultimallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    long countByExample(LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int insert(LitemallMultimall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMultimall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    LitemallMultimall selectOneByExample(LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    LitemallMultimall selectOneByExampleSelective(@Param("example") LitemallMultimallExample example, @Param("selective") LitemallMultimall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    LitemallMultimall selectOneByExampleWithBLOBs(LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    List<LitemallMultimall> selectByExampleSelective(@Param("example") LitemallMultimallExample example, @Param("selective") LitemallMultimall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    List<LitemallMultimall> selectByExampleWithBLOBs(LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    List<LitemallMultimall> selectByExample(LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    LitemallMultimall selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallMultimall.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    LitemallMultimall selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    LitemallMultimall selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMultimall record, @Param("example") LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallMultimall record, @Param("example") LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMultimall record, @Param("example") LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMultimall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallMultimall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMultimall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallMultimallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_multimall
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}